#!/usr/bin/env python3
"""Generate catalog/schema.json from the converter's own tables.

    tools/mkschema.py

The JSON surface was previously only discoverable by reading the minified bundle. This emits
it from `rcj`'s tables rather than a hand-written list, so it cannot drift from what the
converter accepts: when a command is added upstream it appears here on the next run, and when
one is removed it disappears.

Two parts of the output matter as much as the accepted surface:

  refuses              constructs the converter rejects outright. Knowing these up front
                       changes a design; discovering them halfway through does not.
  paint.accepted       probed by compiling a one-key document, not read off a table. Any
                       paint key NOT in this list compiles and is silently dropped, which is
                       the worst failure mode available: the document still reports valid and
                       just does not do what was asked. `rejectedWithMessage` is the safe
                       case - those three raise and say why.
"""

import json
import re
import sys
from pathlib import Path

RCJ = Path("/Users/john/code/github/rcJson")
OUT = Path(__file__).resolve().parent.parent / "catalog" / "schema.json"

sys.path.insert(0, str(RCJ))
from rcj import expr, parser  # noqa: E402

SRC = (RCJ / "rcj" / "parser.py").read_text()

# Commands are recognised by the parser's dispatch, which is a chain of `ctype == "name"`.
COMMANDS = sorted(set(re.findall(r'ctype == "([a-z0-9_]+)"', SRC)))

# Canonical spelling, recovered from the corpus where available: the parser lowercases, so
# the dispatch table cannot tell us that `drawTextAnchored` is camelCase.
def canonical_spellings():
    seen = {}
    docs = Path(__file__).resolve().parent.parent / "docs"
    for p in docs.glob("*/*/doc.json"):
        try:
            text = p.read_text()
        except Exception:
            continue
        for m in re.finditer(r'"([A-Za-z][A-Za-z0-9]*)"\s*:', text):
            k = m.group(1)
            seen.setdefault(k.lower(), k)
    return seen


def probe_paint_keys(rejected):
    """Which paint keys actually survive a compile."""
    import contextlib, io, json as _json
    import rcj
    base = {"header": {"apiLevel": 7, "width": 100, "height": 100, "profiles": 513},
            "root": {"canvas": {"commands": [{"paint": {}},
                     {"drawCircle": {"cx": 50, "cy": 50, "radius": 20}}]}}}
    probe = {"color": "#FF112233", "style": "stroke", "width": 2.0, "strokeCap": "round",
             "strokeJoin": "round", "textSize": 12.0, "antiAlias": True, "shader": "s",
             "colorFilter": "x", "blendMode": "src", "sweepGradient": {}}
    ok = []
    for k, v in probe.items():
        d = _json.loads(_json.dumps(base))
        d["root"]["canvas"]["commands"][0]["paint"] = {k: v}
        try:
            with contextlib.redirect_stdout(io.StringIO()):
                rcj.convert_doc(d)
            ok.append(k)
        except Exception:
            pass
    return sorted(set(ok) - set(rejected))


def main():
    spell = canonical_spellings()
    # Probed, not read off a label. `_PAINT_KEYS_IGNORED` sounds like "accepted and dropped"
    # and is the opposite: those keys RAISE with an explanatory message, which is good
    # behaviour. The genuinely dangerous ones are keys the parser has never heard of - they
    # compile and vanish. Getting this backwards in the schema would have told authors to
    # worry about the safe case and ignore the unsafe one.
    rejected_keys = sorted(re.findall(
        r'"(\w+)"', (re.search(r'_PAINT_KEYS_IGNORED\s*=\s*[\{\(]([^\}\)]*)[\}\)]', SRC)
                      or re.match('', '')).group(1))) if re.search(
        r'_PAINT_KEYS_IGNORED', SRC) else []
    accepted_keys = probe_paint_keys(rejected_keys)

    schema = {
        "generatedFrom": "rcj (the reference Python converter), introspected",
        "note": "Generated by tools/mkschema.py. Do not hand-edit; it will be overwritten.",

        "document": {
            "header": {
                "required": ["width", "height"],
                "common": ["apiLevel", "profiles", "contentDescription"],
                "tags": sorted(__import__("rcj.header", fromlist=["x"]).HEADER_KEY_TO_TAG),
            },
            "root": "a single component object, or a list of them",
        },

        # The form to author in. Both are accepted, so this is guidance rather than a rule -
        # but a generator that picks one and stays with it avoids a whole class of confusion.
        "canonicalForm": {
            "root": "object",
            "paint": "a {\"paint\": {...}} command, not setColor/setStyle/setStrokeWidth",
            "commandSpelling": "keyed by name - {\"drawCircle\": {...}} - not {\"type\": \"drawCircle\"}",
            "wrapper": "a {name, description, json} wrapper is unwrapped automatically",
        },

        "commands": [spell.get(c, c) for c in COMMANDS],

        "paint": {
            "accepted": accepted_keys,
            "rejectedWithMessage": rejected_keys,
            "silentlyDropped": "any key not in `accepted` - e.g. typeface, fontWeight. These "
                               "compile and vanish: the document reports valid and simply "
                               "does not do what was asked. The playground warns (PG2030).",
        },

        "expressions": {
            "functions": sorted(expr.FUNCTIONS),
            "systemVariables": sorted(expr.SYSTEM_VARS),
            "maxRpnTokens": 32,
            "maxRpnTokensNote": "Enforced by the READER, not the writer. An over-long "
                                "expression builds, passes desktop, and fails to load on "
                                "device. Count tokens at generation time.",
            "argumentOrderTraps": {
                "clamp": "clamp(min, max, value) - value LAST. clamp(x, 0, 1) is 0.",
                "ifElse": "ifElse(a, b, c) - condition LAST; b when c > 0, else a.",
                "smooth_step": "smooth_step(value, max, min) - value FIRST. Not clamp's order.",
                "arrayGet": "arrayGet(array, index) - array first.",
            },
        },

        "resources": {
            "sections": ["colors", "floatArrays", "variables", "bitmaps"],
            "note": "Other sections are not read.",
        },

        # Named explicitly because each one costs an author a redesign if found late.
        "refuses": [
            "textMerge - no data-driven text composition; labels must be literals",
            "AGSL/SkSL shader source in JSON",
            "themed colours (light/dark pairs) on canvas paint",
            "typeface, fontWeight or fontStyle on canvas paint",
            "resource sections other than colors, floatArrays, variables, bitmaps",
            "any command not in `commands` - reported as \"canvas command '<lowercased>'\"",
        ],

        "variables": {
            "semantics": "A variable is TEXTUAL SUBSTITUTION, re-evaluated at every @reference "
                         "- not a computed-once binding.",
            "consequences": [
                "Two references to a variable holding rand() give two different numbers.",
                "An unreferenced variable is never evaluated at all.",
                "Names are global and resolved by parse order; loops must use unique names.",
            ],
        },

        "costModel": "One FloatExpression operation per expression FIELD, not per command. "
                     "A drawCircle with four computed arguments is four operations.",
    }

    OUT.parent.mkdir(exist_ok=True)
    OUT.write_text(json.dumps(schema, indent=2) + "\n")
    print(f"  {OUT.relative_to(OUT.parent.parent)}  "
          f"{len(schema['commands'])} commands, "
          f"{len(schema['expressions']['functions'])} functions, "
          f"{len(schema['expressions']['systemVariables'])} system variables, "
          f"{len(schema['refuses'])} documented refusals")


if __name__ == "__main__":
    main()
