#!/usr/bin/env python3
"""Generate catalog/schema.json from the converter's own tables.

    tools/mkschema.py

The JSON surface was previously only discoverable by reading the minified bundle. This emits
it from `rcj`'s tables rather than a hand-written list, so it cannot drift from what the
converter accepts: when a command is added upstream it appears here on the next run, and when
one is removed it disappears.

Two parts of the output matter as much as the accepted surface:

  refuses              constructs the converter rejects outright. Knowing these up front
                       changes a design; discovering them halfway through does not.
  paint                the TWO paint spellings and how they differ, which is not a style
                       question: the ops form raises on an unknown key while the direct-key
                       form silently drops it, and the ops form honours three properties the
                       direct form rejects. Read from the parser's declared tables - probing
                       by "does it compile" cannot tell honoured from dropped, which is what
                       the first version of this file got wrong.
"""

import json
import re
import sys
from pathlib import Path

RCJ = Path("/Users/john/code/github/rcJson")
OUT = Path(__file__).resolve().parent.parent / "catalog" / "schema.json"

sys.path.insert(0, str(RCJ))
from rcj import expr, parser  # noqa: E402

SRC = (RCJ / "rcj" / "parser.py").read_text()

# Commands are recognised by the parser's dispatch, which is a chain of `ctype == "name"`.
COMMANDS = sorted(set(re.findall(r'ctype == "([a-z0-9_]+)"', SRC)))

# Canonical spelling, recovered from the corpus where available: the parser lowercases, so
# the dispatch table cannot tell us that `drawTextAnchored` is camelCase.
def canonical_spellings():
    seen = {}
    docs = Path(__file__).resolve().parent.parent / "docs"
    for p in docs.glob("*/*/doc.json"):
        try:
            text = p.read_text()
        except Exception:
            continue
        for m in re.finditer(r'"([A-Za-z][A-Za-z0-9]*)"\s*:', text):
            k = m.group(1)
            seen.setdefault(k.lower(), k)
    return seen


def paint_surface():
    """The two paint spellings, read from the parser's tables rather than probed.

    Probing by "does it compile" cannot work here, and getting this wrong is what the schema
    was wrong about on its first pass: in the direct-key form an UNKNOWN key compiles, so a
    successful compile proves nothing about whether the key was honoured. The declared tables
    are the only thing that distinguishes "read" from "silently dropped".
    """
    # Every key the ops form honours is a branch of _paint_setter; anything else raises.
    setter = SRC[SRC.index("def _paint_setter("):SRC.index("def _gradient(")]
    ops_keys = sorted(set(re.findall(r'key == "(\w+)"', setter)))

    direct_keys = list(parser._PAINT_KEYS_ORDER)
    direct_raises = sorted(parser._PAINT_KEYS_IGNORED)
    aliases = dict(parser._PAINT_KEY_ALIASES)

    return {
        # Stated first because it is the choice that decides whether a mistake is loud.
        "recommended": "ops",
        "whyOps": "In the ops form an unknown key RAISES, so a typo is an error. In the "
                  "direct-key form an unknown key compiles and is silently dropped, and the "
                  "document reports valid while quietly doing less than asked. The ops form "
                  "also honours more properties, and applies them in written order.",
        "ops": {
            "form": '{"paint": {"ops": [{"color": "#FF3366CC"}, {"style": "fill"}]}}',
            "accepted": ops_keys,
            "unknownKey": "raises NotImplementedComponent",
            "order": "as written",
        },
        "direct": {
            "form": '{"paint": {"color": "#FF3366CC", "style": "fill"}}',
            "accepted": direct_keys,
            "rejectedWithMessage": direct_raises,
            "silentlyDropped": "any other key - antiAlias, typeface, fontWeight, blendMode, "
                               "colorFilter all compile here and vanish",
            "order": "fixed: " + ", ".join(direct_keys) + " - not the order you write them",
        },
        "aliases": aliases,
    }


def main():
    spell = canonical_spellings()
    paint = paint_surface()

    schema = {
        "generatedFrom": "rcj (the reference Python converter), introspected",
        "note": "Generated by tools/mkschema.py. Do not hand-edit; it will be overwritten.",

        "document": {
            "header": {
                "required": ["width", "height"],
                "common": ["apiLevel", "profiles", "contentDescription"],
                "tags": sorted(__import__("rcj.header", fromlist=["x"]).HEADER_KEY_TO_TAG),
            },
            "root": "a single component object, or a list of them",
        },

        # The form to author in. Both are accepted, so this is guidance rather than a rule -
        # but a generator that picks one and stays with it avoids a whole class of confusion.
        "canonicalForm": {
            "root": "object",
            "paint": "the ops array form - {\"paint\": {\"ops\": [...]}} - see `paint.whyOps`",
            "commandSpelling": "keyed by name - {\"drawCircle\": {...}} - not {\"type\": \"drawCircle\"}",
            "wrapper": "a {name, description, json} wrapper is unwrapped automatically",
        },

        "commands": [spell.get(c, c) for c in COMMANDS],

        "paint": paint,

        "expressions": {
            "functions": sorted(expr.FUNCTIONS),
            "systemVariables": sorted(expr.SYSTEM_VARS),
            "maxRpnTokens": 32,
            "maxRpnTokensNote": "Enforced by the READER, not the writer. An over-long "
                                "expression builds, passes desktop, and fails to load on "
                                "device. Count tokens at generation time.",
            "argumentOrderTraps": {
                "clamp": "clamp(min, max, value) - value LAST. clamp(x, 0, 1) is 0.",
                "ifElse": "ifElse(a, b, c) - condition LAST; b when c > 0, else a.",
                "smooth_step": "smooth_step(value, max, min) - value FIRST. Not clamp's order.",
                "arrayGet": "arrayGet(array, index) - array first.",
            },
        },

        "resources": {
            "sections": ["colors", "floatArrays", "variables", "bitmaps"],
            "note": "Other sections are not read.",
        },

        # Named explicitly because each one costs an author a redesign if found late.
        "refuses": [
            "textMerge - no data-driven text composition; labels must be literals",
            "AGSL/SkSL shader source in JSON",
            "themed colours (light/dark pairs) on canvas paint",
            "typeface, fontWeight, fontStyle, antiAlias, blendMode or colorFilter on canvas "
            "paint - note these are SILENTLY DROPPED in the direct-key form and raise in ops",
            "resource sections other than colors, floatArrays, variables, bitmaps",
            "any command not in `commands` - reported as \"canvas command '<lowercased>'\"",
        ],

        "variables": {
            "semantics": "A variable is TEXTUAL SUBSTITUTION, re-evaluated at every @reference "
                         "- not a computed-once binding.",
            "consequences": [
                "Two references to a variable holding rand() give two different numbers.",
                "An unreferenced variable is never evaluated at all.",
                "Names are global and resolved by parse order; loops must use unique names.",
            ],
        },

        "costModel": "One FloatExpression operation per expression FIELD, not per command. "
                     "A drawCircle with four computed arguments is four operations.",
    }

    OUT.parent.mkdir(exist_ok=True)
    OUT.write_text(json.dumps(schema, indent=2) + "\n")
    print(f"  {OUT.relative_to(OUT.parent.parent)}  "
          f"{len(schema['commands'])} commands, "
          f"{len(schema['expressions']['functions'])} functions, "
          f"{len(schema['expressions']['systemVariables'])} system variables, "
          f"{len(schema['refuses'])} documented refusals")


if __name__ == "__main__":
    main()
